export { default as AboutView } from './aboutView';
// export { default as CoverFlowView } from './CoverFlowView';
export { default as HomeView } from './homeView';
export { default as MusicView } from './musicView';
export { default as ArtistsView } from './artistsView';
export { default as ArtistView } from './artistView';
export { default as ElementsView } from './elementsView';
export { default as TimelineView } from './timelineView';
export { default as AlbumsView } from './albumsView';
export { default as AlbumView } from './albumView';
export { default as SettingsView } from './settingsView';
