import { HiddenUnderlineLink } from '@app/components';
import { Tree } from '@app/layout';
import { Components as RenderComponents } from '@app/render-utils';
import { Navigation } from '@app/types';
import { Close, Home } from '@mui/icons-material';
import { Divider, IconButton } from '@mui/material';
import { styled } from '@mui/material/styles';
import { FC } from 'react';

import { DesktopDrawer, MobileDrawer } from '.';
import { NAV_ITEM_INDICATOR_WIDTH } from '../../constants';

const {
  Media: { Media }
} = RenderComponents;

interface DrawerCompProps {
  isDrawerExpanded?: boolean;
  navigation: Navigation;
  handleDrawerOpen?: () => void;
  handleDrawerClose?: () => void;
}
export const DrawerHeader = styled('div')(({ theme }) => {
  return {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingLeft: theme.spacing(2),
    paddingRight: theme.spacing(2 + NAV_ITEM_INDICATOR_WIDTH),
    // Note:
    // The toolbar mixin is necessary for the content to be below the app bar.
    // The minHeight override gets defined in the app theme provider.
    // mixins: {
    //   toolbar: {
    //     minHeight: 64;
    //   }
    // }
    ...theme.mixins.toolbar
  };
});

export const SwitchDrawer: FC<DrawerCompProps> = ({
  isDrawerExpanded,
  navigation = {
    pages: [],
    expandedPages: []
  },
  handleDrawerOpen,
  handleDrawerClose
}) => {
  const { activePage, pages, expandedPages } = navigation;

  const header = (
    <DrawerHeader>
      <IconButton
        onClick={isDrawerExpanded ? handleDrawerClose : handleDrawerOpen}
        component={HiddenUnderlineLink}
        href={{
          pathname: '/'
        }}
        prefetch={false}
      >
        <Home />
      </IconButton>
      <IconButton onClick={handleDrawerClose}>
        <Close />
      </IconButton>
    </DrawerHeader>
  );

  const tree = (
    <Tree pages={pages} expandedPages={expandedPages} activePage={activePage} />
  );

  /**
   * The render props variant of fresnel does not work here.
   * It seems the drawer implementation changes style properties
   * on the HTML body element.
   * Using the render props variant, switching from the drawer's
   * desktop to the mobile version (re-mounts) and vice versa does
   * not properly revert those properties made in the body.
   *
   * Note:
   * Using not the render props version adds an additional div,
   * generated by Media.
   */

  return (
    <>
      <Media lessThan='md'>
        <MobileDrawer
          isDrawerExpanded={isDrawerExpanded}
          handleDrawerOpen={handleDrawerOpen}
          handleDrawerClose={handleDrawerClose}
          sx={{ gridArea: 'app-left' }}
        >
          {header}
          <Divider variant='middle' />
          {tree}
        </MobileDrawer>
      </Media>
      <Media greaterThanOrEqual='md'>
        <DesktopDrawer
          isDrawerExpanded={isDrawerExpanded}
          handleDrawerClose={handleDrawerClose}
          sx={{
            gridArea: 'app-left'
          }}
        >
          {header}
          <Divider variant='middle' />
          {tree}
        </DesktopDrawer>
      </Media>
    </>
  );
};
