export const CHANGE_DEVICE = 'CHANGE_DEVICE';
export const CHANGE_SZENARIO = 'CHANGE_SZENARIO';
export const CHANGE_AREA = 'CHANGE_AREA';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';
export const SET_PROGRESS_OFFSET_Y = 'SET_PROGRESS_OFFSET_Y';
export const SET_PROGRESS_VIEWPORT = 'SET_PROGRESS_VIEWPORT';
